import type { AppDataStore } from "@/lib/types";

const DEMO_DATA: AppDataStore = {
  applications: [
    {
      id: "app-stripe-swe-intern",
      company: "Stripe",
      role: "Software Engineer Intern",
      location: "San Francisco, CA",
      applicationLink: "https://stripe.com/jobs/listing/software-engineer-intern",
      dateApplied: "2026-06-14",
      deadline: "2026-07-20",
      status: "Interview",
      oaReceived: true,
      interviewStage: "Technical Interview",
      recruiterContact: "Alicia Gomez",
      referralStatus: "Received",
      followUpDate: "2026-07-10",
      resumeVersion: "Resume v4",
      notes: "Strong product fit. Focus prep on APIs and distributed systems.",
      interestLevel: 5,
      createdAt: "2026-06-14T14:30:00.000Z",
      updatedAt: "2026-07-02T18:00:00.000Z",
    },
    {
      id: "app-notion-backend-intern",
      company: "Notion",
      role: "Backend Engineer Intern",
      location: "New York, NY",
      applicationLink: "https://www.notion.so/careers",
      dateApplied: "2026-06-18",
      deadline: "2026-07-15",
      status: "OA Received",
      oaReceived: true,
      interviewStage: "None",
      recruiterContact: "Mia Chen",
      referralStatus: "Requested",
      followUpDate: "2026-07-12",
      resumeVersion: "Resume v3",
      notes: "Need to complete the OA before the weekend.",
      interestLevel: 4,
      createdAt: "2026-06-18T16:10:00.000Z",
      updatedAt: "2026-07-05T12:45:00.000Z",
    },
    {
      id: "app-ramp-frontend-intern",
      company: "Ramp",
      role: "Frontend Engineer Intern",
      location: "Remote",
      applicationLink: "https://ramp.com/careers",
      dateApplied: "2026-06-09",
      deadline: "2026-07-11",
      status: "Applied",
      oaReceived: false,
      interviewStage: "None",
      recruiterContact: "Jordan Lee",
      referralStatus: "None",
      followUpDate: "2026-07-09",
      resumeVersion: "Resume v4",
      notes: "Follow up if no response after one week.",
      interestLevel: 4,
      createdAt: "2026-06-09T13:00:00.000Z",
      updatedAt: "2026-06-16T13:00:00.000Z",
    },
    {
      id: "app-datadog-ml-intern",
      company: "Datadog",
      role: "Machine Learning Intern",
      location: "Boston, MA",
      applicationLink: "https://careers.datadoghq.com",
      dateApplied: "2026-05-29",
      deadline: "2026-06-30",
      status: "Rejected",
      oaReceived: false,
      interviewStage: "Completed",
      recruiterContact: "Priya Shah",
      referralStatus: "None",
      followUpDate: null,
      resumeVersion: "Resume v2",
      notes: "Rejected after recruiter screen. Improve ML project framing.",
      interestLevel: 3,
      createdAt: "2026-05-29T15:45:00.000Z",
      updatedAt: "2026-06-24T17:20:00.000Z",
    },
    {
      id: "app-figma-swe-intern",
      company: "Figma",
      role: "Software Engineer Intern",
      location: "New York, NY",
      applicationLink: "https://www.figma.com/careers",
      dateApplied: "2026-06-04",
      deadline: "2026-07-25",
      status: "Offer",
      oaReceived: true,
      interviewStage: "Completed",
      recruiterContact: "Devon Wright",
      referralStatus: "Received",
      followUpDate: null,
      resumeVersion: "Resume v4",
      notes: "Offer in hand. Compare team match and timeline with other roles.",
      interestLevel: 5,
      createdAt: "2026-06-04T18:25:00.000Z",
      updatedAt: "2026-07-07T20:15:00.000Z",
    },
    {
      id: "app-openai-ai-intern",
      company: "OpenAI",
      role: "AI Engineering Intern",
      location: "San Francisco, CA",
      applicationLink: "https://openai.com/careers",
      dateApplied: null,
      deadline: "2026-07-30",
      status: "Wishlist",
      oaReceived: false,
      interviewStage: "None",
      recruiterContact: "",
      referralStatus: "Requested",
      followUpDate: "2026-07-16",
      resumeVersion: "Resume v5",
      notes: "Waiting for referral confirmation before applying.",
      interestLevel: 5,
      createdAt: "2026-07-01T09:00:00.000Z",
      updatedAt: "2026-07-06T21:10:00.000Z",
    },
  ],
  targetCompanies: [
    {
      id: "target-openai",
      company: "OpenAI",
      roleType: "AI",
      applicationSeason: "Fall 2026",
      priorityLevel: "High",
      notes: "Best fit for AI product and systems work.",
      createdAt: "2026-07-01T09:00:00.000Z",
      updatedAt: "2026-07-06T21:10:00.000Z",
    },
    {
      id: "target-coinbase",
      company: "Coinbase",
      roleType: "Backend",
      applicationSeason: "Fall 2026",
      priorityLevel: "High",
      notes: "Monitor internship posting and ask alumni for team context.",
      createdAt: "2026-06-25T11:15:00.000Z",
      updatedAt: "2026-07-03T14:00:00.000Z",
    },
    {
      id: "target-vercel",
      company: "Vercel",
      roleType: "Frontend",
      applicationSeason: "Fall 2026",
      priorityLevel: "Medium",
      notes: "Strong portfolio alignment. Tailor resume around UI and DX work.",
      createdAt: "2026-06-27T10:40:00.000Z",
      updatedAt: "2026-07-02T16:10:00.000Z",
    },
    {
      id: "target-roblox",
      company: "Roblox",
      roleType: "SWE",
      applicationSeason: "Winter 2027",
      priorityLevel: "Medium",
      notes: "Good generalist systems role target.",
      createdAt: "2026-06-21T08:50:00.000Z",
      updatedAt: "2026-06-28T13:20:00.000Z",
    },
  ],
  contacts: [
    {
      id: "contact-nina-openai",
      name: "Nina Patel",
      company: "OpenAI",
      role: "Research Engineer",
      linkedInUrl: "https://www.linkedin.com/in/ninapatel",
      connected: true,
      referralRequested: true,
      referralReceived: false,
      lastContactedDate: "2026-07-06",
      notes: "Sent portfolio and resume. Waiting for referral update.",
      createdAt: "2026-07-02T17:00:00.000Z",
      updatedAt: "2026-07-06T19:15:00.000Z",
    },
    {
      id: "contact-omar-stripe",
      name: "Omar Hassan",
      company: "Stripe",
      role: "Software Engineer",
      linkedInUrl: "https://www.linkedin.com/in/omarhassan",
      connected: true,
      referralRequested: false,
      referralReceived: true,
      lastContactedDate: "2026-06-20",
      notes: "Helpful prep advice for API and data modeling interviews.",
      createdAt: "2026-06-17T20:30:00.000Z",
      updatedAt: "2026-06-20T20:30:00.000Z",
    },
    {
      id: "contact-sara-vercel",
      name: "Sara Kim",
      company: "Vercel",
      role: "Developer Relations Engineer",
      linkedInUrl: "https://www.linkedin.com/in/sarakim",
      connected: false,
      referralRequested: false,
      referralReceived: false,
      lastContactedDate: null,
      notes: "Plan outreach after shipping the portfolio dashboard.",
      createdAt: "2026-06-30T09:20:00.000Z",
      updatedAt: "2026-06-30T09:20:00.000Z",
    },
    {
      id: "contact-eli-notion",
      name: "Eli Brooks",
      company: "Notion",
      role: "Backend Engineer",
      linkedInUrl: "https://www.linkedin.com/in/elibrooks",
      connected: true,
      referralRequested: true,
      referralReceived: true,
      lastContactedDate: "2026-07-04",
      notes: "Confirmed OA format and typical backend interview topics.",
      createdAt: "2026-06-19T13:35:00.000Z",
      updatedAt: "2026-07-04T15:00:00.000Z",
    },
  ],
  weeklyGoals: [
    {
      id: "goal-2026-w27",
      week: "2026-W27",
      applicationGoal: 8,
      applicationsCompleted: 6,
      networkingGoal: 4,
      networkingCompleted: 3,
      leetCodeGoal: 10,
      leetCodeCompleted: 8,
      createdAt: "2026-06-29T08:00:00.000Z",
      updatedAt: "2026-07-05T22:00:00.000Z",
    },
    {
      id: "goal-2026-w28",
      week: "2026-W28",
      applicationGoal: 10,
      applicationsCompleted: 2,
      networkingGoal: 5,
      networkingCompleted: 1,
      leetCodeGoal: 12,
      leetCodeCompleted: 4,
      createdAt: "2026-07-06T08:00:00.000Z",
      updatedAt: "2026-07-08T12:30:00.000Z",
    },
    {
      id: "goal-2026-w29",
      week: "2026-W29",
      applicationGoal: 12,
      applicationsCompleted: 0,
      networkingGoal: 6,
      networkingCompleted: 0,
      leetCodeGoal: 14,
      leetCodeCompleted: 0,
      createdAt: "2026-07-13T08:00:00.000Z",
      updatedAt: "2026-07-13T08:00:00.000Z",
    },
  ],
};

export function createDemoData(): AppDataStore {
  return JSON.parse(JSON.stringify(DEMO_DATA)) as AppDataStore;
}
